<?php

namespace Aeros\App\Queues\Workers;

use Aeros\Src\Classes\Worker;

class AppWorker extends Worker
{
    /**
     * WARNING: DO NOT EDIT THIS FILE, UNLESS YOU KNOW WHAT YOU ARE DOING
     * 
     * This is the main worker for the application. It handles all the registered
     * pipelines (Jobs) in the queue systeme (Redis).
     *
     * @return void
     */
    public function handle()
    {
        app()->queue->processPipeline();
    }

    /**
     * Calls the requested worker and puts it to do its job.
     *
     * @param string|array $worker or an array workers
     * @return void
     */
    public function call(string|array $worker)
    {
        $workers = is_string($worker) ? [$worker] : $worker;

        foreach ($workers as $w) {
            if (! $this->isWorker($w)) {
                throw new \Exception(
                    sprintf('ERROR[Worker] There was a problem validating worker \'%s\.', $w)
                );
            }

            (new $w)->handle();
        }
    }

    /**
     * Calls all the registered workers in ./config/workers.php.
     *
     * @return void
     */
    public function callAll(array $workers = [])
    {
        $workers = ! empty($workers) ? $workers : config('workers');

        if (is_array($workers) && ! empty($workers)) {
            foreach ($workers as $worker) {
                $this->call($worker);
            }
        }
    }

    /**
     * Initiates a worker infinite loop.
     *
     * @param Worker|string $worker
     * @return void
     */
    public function startWorker(Worker|string $worker)
    {
        if (is_string($worker) && is_subclass_of($worker, Worker::class)) {
            (new $worker)->start();
        }
    }

    /**
     * Checks if a worker is valid.
     *
     * @param string $worker
     * @return boolean
     */
    private function isWorker(string $worker): bool
    {
        return (class_exists($worker) && get_parent_class($worker) == Worker::class);
    }
}
